[package]
name = "ethers-rs-aws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
ethers = "2.0.11"
thiserror = "1.0.50"
